# kubernetes/02-secrets.yml
apiVersion: v1
kind: Secret
metadata:
  name: fiscalgo-secrets
  namespace: fiscalgo-app
type: Opaque
data:
  POSTGRES_PASSWORD: "MDEwMjA0"
  MINIO_ROOT_USER: "dXNlcm1pbmlv"
  MINIO_ROOT_PASSWORD: "MDEwMjA0MDk="