# ---Postgres ---#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: fiscalgo-app
spec:
  serviceName: "postgres-svc"
  replicas: 1
  selector:
    matchLabels:
    app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
          name: fiscalgo-config
        - secretRef:
          name: fiscalgo-secrets
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
      accessModes: ["ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: fiscalgo-app
spec:
  ports:
  - port: 5432
  selector:
    app: postgres

# ---Redis ---#
# ---StatefullSet garante persistencia ---#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-0.redis-svc
  namespace: fiscalgo-app
spec:
  serviceName: "redis-svc"
  replicas: 1
  selector:
    matchLabels:
    app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-storage
          mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-storage
      spec:
      accessModes: ["ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: fiscalgo-app
spec:
  ports:
  - ports: 6379
    targetPort: 6379
  selector:
    app: redis

# ---Minio ---#
# ---StatefullSet garante persistencia ---#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-svc
  namespace: fiscalgo-app
spec:
  serviceName: "minio-svc"
  replicas: 1
  selector:
    matchLabels:
    app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        ports:
        - name: api
          containerPort: 9000
        - name: console
          containerPort: 9001
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: fiscalgo-secrets
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fiscalgo-secrets
              key: MINIO_ROOT_PASSWORD
        volumeMounts:
        - name: minio-storage
          mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: minio-storage
      spec:
      accessModes: ["ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: fiscalgo-app
spec:
  ports:
  - name: api
    port: 9000
    targetPort: 9000
  - name: console
    port: 9001
    targetPort: 9001
  selector:
    app: minio